# Generated by Django 2.0.1 on 2018-01-10 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    UserModel = getattr(settings, 'FITAPP_USER_MODEL', 'auth.User')
    dependencies = [
        ('fitapp', '0008_remove_userfitbit_auth_secret'),
        migrations.swappable_dependency(UserModel),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseriesdata',
            name='date',
            field=models.DateField(help_text='The date the data was recorded'),
        ),
        migrations.AlterField(
            model_name='timeseriesdata',
            name='resource_type',
            field=models.ForeignKey(help_text='The type of time series data',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to='fitapp.TimeSeriesDataType'),
        ),
        migrations.AlterField(
            model_name='timeseriesdata',
            name='user',
            field=models.ForeignKey(help_text="The data's user",
                                    on_delete=django.db.models.deletion.CASCADE,
                                    to=UserModel),
        ),
        migrations.AlterField(
            model_name='timeseriesdata',
            name='value',
            field=models.CharField(default=None,
                                   help_text='The value of the data. This is typically a number, though saved as a string here. The units can be inferred from the data type. For example, for step data the value might be "9783" (the units) would be "steps"',
                                   max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='timeseriesdatatype',
            name='category',
            field=models.IntegerField(
                choices=[(0, 'foods'), (1, 'activities'), (2, 'sleep'), (3, 'body')],
                help_text='The category of the time series data, one of: 0(foods), 1(activities), 2(sleep), 3(body)'),
        ),
        migrations.AlterField(
            model_name='timeseriesdatatype',
            name='resource',
            field=models.CharField(
                help_text='The specific time series resource. This is the string that will be used for the [resource-path] of the API url referred to in the Fitbit documentation',
                max_length=128),
        ),
        migrations.AlterField(
            model_name='userfitbit',
            name='access_token',
            field=models.TextField(help_text='The OAuth2 access token'),
        ),
        migrations.AlterField(
            model_name='userfitbit',
            name='expires_at',
            field=models.FloatField(
                help_text='The timestamp when the access token expires'),
        ),
        migrations.AlterField(
            model_name='userfitbit',
            name='fitbit_user',
            field=models.CharField(help_text='The fitbit user ID', max_length=32,
                                   unique=True),
        ),
        migrations.AlterField(
            model_name='userfitbit',
            name='refresh_token',
            field=models.TextField(help_text='The OAuth2 refresh token'),
        ),
        migrations.AlterField(
            model_name='userfitbit',
            name='user',
            field=models.OneToOneField(help_text='The user',
                                       on_delete=django.db.models.deletion.CASCADE,
                                       to=UserModel),
        ),
    ]
