# Generated by Django 2.0.6 on 2018-07-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0010_auto_20180710_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfitbit',
            name='last_intraday_step_data_datetime',
            field=models.DateTimeField(default=None),
        ),
    ]
