# Generated by Django 2.0.6 on 2018-07-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitapp', '0011_userfitbit_last_intraday_step_data_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfitbit',
            name='last_intraday_step_data_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
